runtime: nodejs18
service: default
# service: frontend
instance_class: B2
#automatic_scaling:
 # min_idle_instances: 1
  #min_instances: 1
  #max_instances: 1

basic_scaling:
  max_instances: 11
  idle_timeout: 10m


handlers:
  - url: /
    static_files: dist/new-tower-app/index.html
    upload: dist/new-tower-app/index.html
  - url: /
    secure: always
    static_dir: dist/new-tower-app
